/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExaFinal2009_10.java
 *
 * Created on 07-jun-2010, 17:23:24
 */

package PqUd8;

import javax.swing.JOptionPane;

/**
 *
 * @author p
 */
public class Apuesta extends javax.swing.JFrame {

    
    public Apuesta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panApuesta = new javax.swing.JPanel();
        txfImporte = new javax.swing.JTextField();
        lblImporte = new javax.swing.JLabel();
        txfEquipo = new javax.swing.JTextField();
        lblEquipo = new javax.swing.JLabel();
        panResultado = new javax.swing.JPanel();
        lblPremio = new javax.swing.JLabel();
        txfPremio = new javax.swing.JTextField();
        btnVerificarPremio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MisApuestas.com");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panApuesta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Apuesta ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        txfImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfImporte.setText("0");
        txfImporte.setNextFocusableComponent(txfEquipo);
        txfImporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfImporteFocusGained(evt);
            }
        });

        lblImporte.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblImporte.setText("Importe");

        txfEquipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txfEquipo.setNextFocusableComponent(btnVerificarPremio);
        txfEquipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfEquipoFocusGained(evt);
            }
        });

        lblEquipo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblEquipo.setText("Equipo");

        javax.swing.GroupLayout panApuestaLayout = new javax.swing.GroupLayout(panApuesta);
        panApuesta.setLayout(panApuestaLayout);
        panApuestaLayout.setHorizontalGroup(
            panApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panApuestaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblImporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panApuestaLayout.setVerticalGroup(
            panApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panApuestaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImporte)
                    .addComponent(lblEquipo)
                    .addComponent(txfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Resultado ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        lblPremio.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblPremio.setText("Premio");

        txfPremio.setEditable(false);
        txfPremio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfPremio.setText("0");
        txfPremio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfPremio.setEnabled(false);
        txfPremio.setFocusable(false);

        javax.swing.GroupLayout panResultadoLayout = new javax.swing.GroupLayout(panResultado);
        panResultado.setLayout(panResultadoLayout);
        panResultadoLayout.setHorizontalGroup(
            panResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResultadoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblPremio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfPremio)
                .addGap(80, 80, 80))
        );
        panResultadoLayout.setVerticalGroup(
            panResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPremio))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnVerificarPremio.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnVerificarPremio.setMnemonic('V');
        btnVerificarPremio.setText("Verificar Premio");
        btnVerificarPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarPremioActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.setNextFocusableComponent(txfImporte);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSalir)
                            .addComponent(panApuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVerificarPremio)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerificarPremio)
                .addGap(18, 18, 18)
                .addComponent(panResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnSalir)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void limpiaPantalla()
    {
        //Incializa valores como en pantalla inicial
        txfImporte.setText("0");
        txfEquipo.setText("");
        txfPremio.setText("0");
        
        txfImporte.requestFocus();
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rootPane.setDefaultButton(btnVerificarPremio);
        
        txfImporte.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private boolean todoDigitos (String cadena)
    {   
        //Devuelve verdadero si todos los caracteres de la cadena son dígitos.
        //Se considera la cadena sin espacios en los laterales.
        //La cadena puede estar vacía

        boolean todoDigitos;
        int k;

        todoDigitos = true;

        //Recorremos el contenido de cadena
        k = 0;
        while (  (k<= cadena.length()-1) &&  (todoDigitos == true))
        {
            // Si NO es dígito
            if ( ! (Character.isDigit(cadena.charAt(k))) )
            {
                todoDigitos = false;
            }

            k = k+1;
        }//FIN Recorremos el contenido de cadena

        return todoDigitos;
    }


    private boolean validaImporte()
    {// ----- Valida el campo Importe
        boolean continua;
        String importeStr;

        importeStr = (txfImporte.getText());

        continua = true;//Todo está válido

        //Si algún caracter no es dígito
        //Falta añadir control negativos!!!!!!!
        if ( (continua == true) && (todoDigitos(importeStr) == false) )
        {
            continua = false;
            JOptionPane.showMessageDialog(this, "Sólo se admiten números",
                    "Error en Importe",  JOptionPane.ERROR_MESSAGE);
        } // FIN Si algún caracter no es dígito

        
        // Si el importe es cero[no preguntamos si el num es <0 ya que ello
        //implicaría que habríamos tecleado el char "-", y ello es imposible
        //ya que en la validación anterior hubiera sido detectado como NO dígito
        if ( (continua == true) && (Integer.parseInt(importeStr)<=0) )
        {
            continua = false;
            JOptionPane.showMessageDialog(this, "Campo mayor que cero",
                    "Error en Importe",  JOptionPane.ERROR_MESSAGE);
        }  // FIN Si el importe es cero
        
        // Si ha habido error
        if (continua == false)
        {
            
            txfImporte.requestFocus(); // Enviamos foco a campo erróneo
        }

        return continua;
    }// FIN validaImporte()


    private char[]  informaArray(char[] arrLetras, String nombre)
    {
        //Rellena el array que se le pasa como parámetro con los caracteres que 
        //componen el nombre)
        //devuelve el array rellenado
        int k;
        
        for (k=0;k<= nombre.length()-1; k= k+1)
        {
            arrLetras[k] = nombre.charAt(k);
        }

        return arrLetras;
    }


    private void creaApdeportiva()
    {
        ApuestaDeportivaCorregido apDep;

        //Creamos objeto apuesta deportiva:
        apDep = new ApuestaDeportivaCorregido(Integer.parseInt(txfImporte.getText()),
                    Integer.parseInt(txfPremio.getText()), txfEquipo.getText() );
//apDep.muestraDatos();
    }

    private void btnVerificarPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarPremioActionPerformed
        char arrLetrasEquipo[];
        
        

//int k; //Sólo para probar efectividad método informaArray

        arrLetrasEquipo = new char[txfEquipo.getText().length()];

        txfPremio.setText("0"); //Inicializamos Premio por si en la apuesta anterior hubo premio

        //Si se cumplen las validaciones(el importe es válido)
        if ( validaImporte() == true)
        {
            //Si coincide el equipo con el ganador("Villarreal")
            if (txfEquipo.getText().equals("Villarreal") )
            {
                //Actualizamos premio
                txfPremio.setText("" + (Integer.parseInt(txfImporte.getText()) * 10));
                
                txfEquipo.requestFocus();

                //Informamos array
                arrLetrasEquipo = informaArray(arrLetrasEquipo, txfEquipo.getText());
                creaApdeportiva(); //crea objeto de Apuesta Deportiva(mejorar esto para que no se repita)
////Sólo para probar efectividad método informaArray:
//for (k=0; k<=txfEquipo.getText().length()-1; k= k+1)
//{
//    System.out.println(arrLetrasEquipo[k]);
//}
            } //FIN Si coinciden los equipos

            else //Si NO coinciden los equipos(no acertó)
            {
                creaApdeportiva(); //crea objeto de Apuesta Deportiva(mejorar esto para que no se repita)
//System.out.println("entro");
                limpiaPantalla();
            }

        }//FIN Si el importe es válido
    }//GEN-LAST:event_btnVerificarPremioActionPerformed

    private void txfImporteFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txfImporteFocusGained
    {//GEN-HEADEREND:event_txfImporteFocusGained
        // TODO add your handling code here:
        txfImporte.selectAll(); // seleccionamos todo el contenido
    }//GEN-LAST:event_txfImporteFocusGained

    private void txfEquipoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txfEquipoFocusGained
    {//GEN-HEADEREND:event_txfEquipoFocusGained
        // TODO add your handling code here:
        txfEquipo.selectAll();
    }//GEN-LAST:event_txfEquipoFocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_16_Corregido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerificarPremio;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblPremio;
    private javax.swing.JPanel panApuesta;
    private javax.swing.JPanel panResultado;
    private javax.swing.JTextField txfEquipo;
    private javax.swing.JTextField txfImporte;
    private javax.swing.JTextField txfPremio;
    // End of variables declaration//GEN-END:variables

}
